# Generated by Django 5.1.3 on 2024-11-09 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncreator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_creator_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donator_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
