# Generated by Django 5.1.3 on 2024-11-09 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0003_useraccount_alter_campaigncreator_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncreator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DHopeNation.useraccount'),
        ),
        migrations.AlterField(
            model_name='donator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DHopeNation.useraccount'),
        ),
    ]
