# Generated by Django 5.1.3 on 2024-11-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0004_alter_campaigncreator_user_alter_donator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='honor',
            field=models.CharField(default='Neutral Honor', max_length=100),
        ),
        migrations.AlterField(
            model_name='donator',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
