# Generated by Django 5.1.3 on 2024-11-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0005_alter_donator_honor_alter_donator_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donator',
            old_name='donaiton_value',
            new_name='donation_value',
        ),
    ]
