# Generated by Django 5.1.3 on 2024-11-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0006_rename_donaiton_value_donator_donation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='donation_value',
            field=models.FloatField(default=0),
        ),
    ]
