# Generated by Django 5.1.3 on 2024-11-13 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0007_alter_donator_donation_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.TextField(default='[]')),
                ('goal', models.FloatField()),
                ('current_amount', models.FloatField(default=0)),
                ('total_donators', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('campaign_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHopeNation.campaigncreator')),
            ],
        ),
    ]
