# Generated by Django 5.1.3 on 2024-11-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0008_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sentence',
            field=models.CharField(default='No sentence', max_length=100),
        ),
    ]
