# Generated by Django 5.1.3 on 2024-11-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0009_campaign_ratio_campaign_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
