# Generated by Django 5.1.3 on 2024-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0011_alter_campaign_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to='identification/'),
        ),
    ]
