# Generated by Django 5.1.3 on 2024-11-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0012_useraccount_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign-images/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHopeNation.campaign')),
            ],
        ),
    ]
