# Generated by Django 5.1.3 on 2024-11-23 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0013_campaignimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='total_donators',
            new_name='total_donors',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_donator',
            new_name='is_donor',
        ),
        migrations.RenameModel(
            old_name='Donator',
            new_name='Donor',
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHopeNation.campaign')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DHopeNation.donor')),
            ],
        ),
    ]
