# Generated by Django 5.1.3 on 2024-11-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0015_donation_campaign_title_donation_donor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='campaign_title',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_username',
        ),
    ]
