# Generated by Django 5.1.3 on 2024-11-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0017_alter_donor_donation_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donation_history',
        ),
    ]
