# Generated by Django 5.1.3 on 2024-11-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHopeNation', '0020_remove_campaign_category_campaign_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='categories',
            new_name='category',
        ),
    ]
